# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EEG_ALFA_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from mplwidget import MplWidget
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 539)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(85, 0, 0);")
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout.addWidget(self.MplWidget)
        self.label_estado = QtWidgets.QLabel(self.centralwidget)
        self.label_estado.setMaximumSize(QtCore.QSize(16777215, 61))
        self.label_estado.setStyleSheet("background-color: rgb(0, 85, 127);\n"
"")
        self.label_estado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_estado.setObjectName("label_estado")
        self.verticalLayout.addWidget(self.label_estado)
        self.pushButton_signal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_signal.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_signal.setMaximumSize(QtCore.QSize(16777215, 61))
        self.pushButton_signal.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_signal.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(203, 203, 216);")
        self.pushButton_signal.setObjectName("pushButton_signal")
        self.verticalLayout.addWidget(self.pushButton_signal)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setStyleSheet("background-color: rgb(204, 204, 204);\n""")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.actionrtthtg = QtWidgets.QAction(MainWindow)
        self.actionrtthtg.setObjectName("actionrtthtg")
        self.actionvdvf = QtWidgets.QAction(MainWindow)
        self.actionvdvf.setObjectName("actionvdvf")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_estado.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">No hay datos guardados</span></p></body></html>"))
        self.pushButton_signal.setText(_translate("MainWindow", "Iniciar Toma de Datos"))
        self.actionrtthtg.setText(_translate("MainWindow", "Iniciar Lectura"))
        self.actionvdvf.setText(_translate("MainWindow", "vdvf"))
from mplwidget import MplWidget
